typography_spectrum: 0.74251
color:
  brandColors:
    - '#000000'
    - '#c0bfc4'
    - '#ffc500'
    - '#8e3d46'
    - '#36a690'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74248
analytics:
  google: null
  facebook: null
  twitter: null
name: andymalhan
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: This and that
description: 'Ramblings about this, that and the other'
purpose: []
