name: andymalhan
favicon: null
layout_spectrum: 0.74248
typography_spectrum: 0.1361832998227328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c0bfc4'
    - '#ffc500'
    - '#8e3d46'
    - '#36a690'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
